import registeredFunctions from "../confect/_generated/registeredFunctions/memberships";

export const accept = registeredFunctions.accept;
export const detachExternalInvitation = registeredFunctions.detachExternalInvitation;
export const ensureUnitAccess = registeredFunctions.ensureUnitAccess;
export const getInvitationDeliveryTarget = registeredFunctions.getInvitationDeliveryTarget;
export const getUnitAccessTarget = registeredFunctions.getUnitAccessTarget;
export const handleExternalMembershipChange = registeredFunctions.handleExternalMembershipChange;
export const handleInvitationDeliveryComplete = registeredFunctions.handleInvitationDeliveryComplete;
export const invitationDeliveryWorkflow = registeredFunctions.invitationDeliveryWorkflow;
export const invite = registeredFunctions.invite;
export const list = registeredFunctions.list;
export const myAccess = registeredFunctions.myAccess;
export const prepareExternalInvitation = registeredFunctions.prepareExternalInvitation;
export const recordExternalInvitation = registeredFunctions.recordExternalInvitation;
export const reject = registeredFunctions.reject;
export const releaseExternalInvitation = registeredFunctions.releaseExternalInvitation;
export const resendInvitation = registeredFunctions.resendInvitation;
export const revoke = registeredFunctions.revoke;
export const sendInvitationEmail = registeredFunctions.sendInvitationEmail;
export const startInvitationDelivery = registeredFunctions.startInvitationDelivery;
export const syncUnitAccess = registeredFunctions.syncUnitAccess;
export const terminalizeInvitationDelivery = registeredFunctions.terminalizeInvitationDelivery;
export const updateOccupancyType = registeredFunctions.updateOccupancyType;
export const withdrawInvitation = registeredFunctions.withdrawInvitation;
