import { useQuery } from '@confect/react';
import { createFileRoute } from '@tanstack/react-router';
import { ArrowRight, FileSpreadsheet } from 'lucide-react';

import refs from '@repo/backend/refs';
import { Skeleton } from '@repo/ui';

import * as CommonUI from '#modules/common-ui';
import * as VisitPass from '#modules/visit-pass';
import * as MembershipRouteFeat from '#routes/_authenticated/app/m/$membershipId/-feat';
import * as AdminRouteFeat from '#routes/_authenticated/app/m/$membershipId/admin/-feat';

export const Route = createFileRoute(
  '/_authenticated/app/m/$membershipId/admin/reportes/'
)({
  component: AdminShiftReportsPage,
});

/** The unit's latest Reportes de turno, generated by Porteros or from Turnos. */
function AdminShiftReportsPage() {
  const membership = MembershipRouteFeat.useCurrentMembership();
  const reports = useQuery(refs.public.shiftReports.listForUnit, {
    membershipId: membership.membershipId,
  });

  const goToShifts = (
    <CommonUI.NavLinkButton
      to="/app/m/$membershipId/admin/turnos"
      params={{ membershipId: membership.membershipId }}
      variant="outline"
    >
      Ir a Turnos
      <ArrowRight aria-hidden="true" />
    </CommonUI.NavLinkButton>
  );

  return (
    <>
      <VisitPass.PageHeader
        eyebrow="Portería"
        title="Reportes de turno"
        description="El Excel con las Visitas de cada Turno. Los Porteros los generan al cerrar su Turno; tú puedes generarlos desde Turnos."
        actions={goToShifts}
      />

      <AdminRouteFeat.QueryView
        result={reports}
        loading={
          <div className="flex flex-col gap-3">
            <Skeleton className="h-20" />
            <Skeleton className="h-20" />
          </div>
        }
      >
        {(value) =>
          value.length === 0 ? (
            <VisitPass.EmptyState
              icon={FileSpreadsheet}
              title="Aún no hay Reportes de turno"
              description="Abre un Turno en curso o cerrado y genera su reporte para descargarlo o enviarlo por correo."
              action={goToShifts}
            />
          ) : (
            <div className="grid gap-3 md:grid-cols-2">
              {value.map((report) => (
                <AdminRouteFeat.ShiftReportItem
                  key={report._id}
                  report={report}
                  timeZone={membership.residentialUnitTimeZone}
                />
              ))}
            </div>
          )
        }
      </AdminRouteFeat.QueryView>
    </>
  );
}
